apiVersion: v1
kind: Service
metadata:
  name: payment-status-microservice
spec:
  selector:
    app: payment-status-microservice
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: ClusterIP